export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_USERS = "GET_USERS";
export const GET_USER = "GET_USER";
export const ADD_USER = "ADD_USER";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_STATUS = "UPDATE_USER_STATUS";
export const DELETE_USER = "DELETE_USER";
export const USER_LOADING = "USER_LOADING";

export const GET_FABRICANT_USERS = "GET_FABRICANT_USERS";
export const ADD_FABRICANT_USER = "ADD_FABRICANT_USER";
export const DELETE_FABRICANT_USER = "DELETE_FABRICANT_USER";
export const UPDATE_FABRICANT_USER = "UPDATE_FABRICANT_USER";

export const ADD_FABRICANT = "ADD_FABRICANT";
export const UPDATE_FABRICANT = "UPDATE_FABRICANT";
export const GET_FABRICANTS = "GET_FABRICANTS";
export const GET_FABRICANT = "GET_FABRICANT";
export const DELETE_FABRICANT = "DELETE_FABRICANT";

export const GET_BRANDS = "GET_BRANDS";
export const GET_BRAND = "GET_BRAND";
export const ADD_BRAND = "ADD_BRAND";
export const UPDATE_BRAND = "UPDATE_BRAND";
export const DELETE_BRAND = "DELETE_BRAND";
export const GET_MODEL = "GET_MODEL";
export const ADD_MODEL = "ADD_MODEL";
export const UPDATE_MODEL = "UPDATE_MODEL";
export const MODEL_LOADING = "MODEL_LOADING";

export const GET_MODELS = "GET_MODELS";
export const GET_FAB_BRANDS = "GET_FAB_BRANDS";
export const DELETE_MODEL = "DELETE_MODEL";
export const SET_CURRENT_MODEL = "SET_CURRENT_MODEL";

export const GET_COLORS = "GET_COLORS";
export const GET_COLOR = "GET_COLOR";
export const ADD_COLOR = "ADD_COLOR";
export const UPDATE_COLOR = "UPDATE_COLOR";
export const DELETE_COLOR = "DELETE_COLOR";
export const COLOR_LOADING = "COLOR_LOADING";

export const GET_OPTIONS = "GET_OPTIONS";
export const GET_OPTION = "GET_OPTION";
export const ADD_OPTION = "ADD_OPTION";
export const UPDATE_OPTION = "UPDATE_OPTION";
export const DELETE_OPTION = "DELETE_OPTION";
export const OPTION_LOADING = "OPTION_LOADING";

export const GET_ORDERS = "GET_ORDERS";
export const ACCEPT_ORDER = "ACCEPT_ORDER";
export const REJECT_ORDER = "REJECT_ORDER";
export const ORDER_LOADING = "ORDER_LOADING";

export const ADD_VERSION = "ADD_VERSION";
export const VERSION_LOADING = "VERSION_LOADING";
export const GET_VERSIONS = "GET_VERSIONS";
export const UPDATE_VERSION = "UPDATE_VERSION";
export const DELETE_VERSION = "DELETE_VERSION";
export const GET_VERSION = "GET_VERSION";
export const GET_VEHICLES_BY_MANUFACTURER = "GET_VEHICLES_BY_MANUFACTURER";
export const ADD_VEHICLE = "ADD_VEHICLE";
